### ISSUE TITLE
[Help] Issue on setting up the local development env

### ISSUE THREAD

**Issue by Aju100** [web-telescope/Scan8#79]
Hi everyone,

As far as I have gone through README.md of scan8, I have got the issue on setting up the local environment in my machine.

## First approach
I have gone through Docker one isolating the env so we can run easily. But the issue raises up.

> make sure you have to install docker.
<b>Steps to reproduce.</b>
-  Fork and  ```git clone repo_url``` 
- cd Scan8/Dockerfiles/Dashboard+Coordinator/
-  ```docker build -t name_of_build_image . ```

Here are the failed logs via docker setup.
![cop](https://user-images.githubusercontent.com/29862610/155734655-1c346084-a806-49a1-b7b3-27d6f43d762d.png)

<b>It has already said there is no folder of that in order to copy in the docker storage/volume correct me if i am wrong here </b>

## Second approach
I have to set up the rest of the other tools like MongoDB, Redis, Python, and clamav too for the plain installation process.
Make sure my Redis and MongoDB working on the background.
<b>Mongodb</b>
![db](https://user-images.githubusercontent.com/29862610/155735914-21e9a10b-eda9-4642-bd62-dc1a97b5e381.png)
<b>Redis</b>
![re](https://user-images.githubusercontent.com/29862610/155735981-11653454-df59-448d-9dce-0d0804ea3d5e.png)

<b>Steps to reproduce</b>
- I assume you have cloned and are already in the directory
- ```cd Dashboard```
- ```pip3 install -r requirements.txt```
-  ```python3 app.py```, flask server listens to the port on 5000 on localhost

Here is the output
![ser](https://user-images.githubusercontent.com/29862610/155736982-93d899f6-7c9e-4f9f-aa72-80154e3e9b65.png)

I would love to know what causes the issue and fully set it up in my local machine so I can learn and enhance this project. Looking forward to hear from the community.

**Comment by maanas-talwar** [comment]
Hi @Aju100,
I believe the pymongo library version might be posing problems. Try downgrading it as mentioned in this [link](https://stackoverflow.com/questions/69768628/pymongo-errors-serverselectiontimeouterror-error-with-mongodb-atlas-and-flask).

**Comment by maanas-talwar** [comment]
Hi @Aju100,
Changing ```MONGODB_HOST="mongo-service"``` to ```MONGODB_HOST="127.0.0.1"``` in the ```.env``` file should fix it.

The issue arises due to 2 main reasons, firstly, correct environment variables are needed by the project to interact with other components like MongoDB, which can be fixed as stated above. Secondly, as highlighted [here](https://stackoverflow.com/questions/37705231/pymongo-error-server-timeout), it may be the case that MongoDB is not listening on localhost mapped to IPv6. This can be resolved by editing the MongoDB config file. 

For location of MongoDB config file refer [this](https://docs.mongodb.com/manual/reference/configuration-options/).
For changing the config file to enable MongoDB to listen to IPv6 refer [this](https://dba.stackexchange.com/questions/173781/bind-mongodb-to-ipv4-as-well-as-ipv6).

**Comment by Aju100** [comment]
Hi @maanas-talwar thank you it's working now.

**Comment by Aju100** [comment]
@maanas-talwar How about the first approach can you please test it on your machine?
